/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#236d00',
        'primary-container': '#68b946',
        'on-primary': '#ffffff',
        'on-primary-container': '#144500',
        'primary-fixed': '#a2f87c',
        'primary-fixed-dim': '#87db63',
        'on-primary-fixed': '#062100',
        'on-primary-fixed-variant': '#195200',
        'inverse-primary': '#87db63',
        secondary: '#5f5e5e',
        'secondary-container': '#e5e2e1',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#656464',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1c1b1b',
        'on-secondary-fixed-variant': '#474646',
        tertiary: '#5e5e5f',
        'tertiary-container': '#a6a6a6',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#3b3c3c',
        'tertiary-fixed': '#e3e2e2',
        'tertiary-fixed-dim': '#c7c6c6',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#464747',
        background: '#f6fbed',
        'on-background': '#181d15',
        surface: '#f6fbed',
        'surface-bright': '#f6fbed',
        'surface-dim': '#d7dcce',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f5e8',
        'surface-container': '#ebf0e2',
        'surface-container-high': '#e5eadc',
        'surface-container-highest': '#dfe4d7',
        'surface-variant': '#dfe4d7',
        'surface-tint': '#236d00',
        'on-surface': '#181d15',
        'on-surface-variant': '#40493a',
        'inverse-surface': '#2d3229',
        'inverse-on-surface': '#eef3e5',
        outline: '#707a69',
        'outline-variant': '#c0cab6',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        h1: ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        h2: ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        h3: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '600' }],
        button: ['16px', { lineHeight: '1', fontWeight: '600' }],
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        margin: '32px',
        base: '8px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0px 4px 12px rgba(0,0,0,0.05)',
        green: '0px 4px 12px rgba(104,185,70,0.3)',
      },
    },
  },
  plugins: [],
}
