// ─── MOCK USERS ──────────────────────────────────────────────────────────────
export const CURRENT_USER = {
  id: 'u1',
  name: 'Arjun Mehra',
  email: 'arjun.mehra@university.edu',
  avatar: 'https://i.pravatar.cc/150?img=11',
  institution: 'VIT University',
  degree: 'B.Tech Computer Science',
  gradYear: '2025',
  role: 'doer', // 'asker' | 'doer'
  reliabilityScore: 94,
  rating: 4.8,
  completedTasks: 22,
  totalEarned: 12450,
  verified: true,
};

export const MOCK_USERS = [
  {
    id: 'u2',
    name: 'Alex Chen',
    avatar: 'https://i.pravatar.cc/150?img=3',
    rating: 4.9,
    successRate: 98,
    completedTasks: 45,
    verified: true,
    bio: "Hey! I'm already at the library studying for my chem final. Can grab those books for you right now.",
  },
  {
    id: 'u3',
    name: 'Maya Patel',
    avatar: 'https://i.pravatar.cc/150?img=5',
    rating: 5.0,
    successRate: 100,
    completedTasks: 63,
    verified: true,
    bio: "I have a bike so I can get these to you in under 10 minutes. Super reliable and frequent helper!",
  },
  {
    id: 'u4',
    name: 'Jordan Smith',
    avatar: 'https://i.pravatar.cc/150?img=7',
    rating: 4.7,
    successRate: 92,
    completedTasks: 31,
    verified: true,
    bio: "Just finished classes for the day and heading that way. Happy to help out!",
  },
  {
    id: 'u5',
    name: 'James W.',
    avatar: 'https://i.pravatar.cc/150?img=8',
    rating: 4.6,
    successRate: 89,
    completedTasks: 18,
    verified: true,
    bio: "Regular campus helper. Quick turnaround guaranteed.",
  },
];

// ─── MOCK TASKS ───────────────────────────────────────────────────────────────
export const MOCK_TASKS = [
  {
    id: 't1',
    title: 'Calculus II Tutoring',
    category: 'Academic',
    description: 'Need help with integration by parts and series convergence. 1-hour session preferred at Main Library.',
    location: 'Main Library',
    distance: '0.5 km away',
    payout: 800,
    deadline: '2026-04-28T14:00:00',
    postedAt: new Date(Date.now() - 12 * 60000).toISOString(),
    status: 'open',
    askerId: 'u2',
    askerName: 'Alex Chen',
    askerAvatar: 'https://i.pravatar.cc/150?img=3',
    applicants: [],
    assignedDoerId: null,
    proof: null,
    requirements: ['Must be comfortable with Calculus II syllabus', 'Bring own study material if possible'],
    urgent: false,
  },
  {
    id: 't2',
    title: 'Print & Submit Assignment',
    category: 'Errand',
    description: 'Need someone to print my assignment PDF and submit it to the CSE department office (Room 204) before 3 PM.',
    location: 'CSE Department Office',
    distance: '0.2 km away',
    payout: 300,
    deadline: '2026-04-28T15:00:00',
    postedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    status: 'open',
    askerId: 'u3',
    askerName: 'Maya Patel',
    askerAvatar: 'https://i.pravatar.cc/150?img=5',
    applicants: [],
    assignedDoerId: null,
    proof: null,
    requirements: ['Must show submission receipt', 'Printing cost will be reimbursed'],
    urgent: true,
  },
  {
    id: 't3',
    title: 'Flyer Distribution on Campus',
    category: 'Events',
    description: 'Distribute 200 event flyers across the main campus areas including hostels and cafeteria.',
    location: 'Student Union',
    distance: '1.1 km away',
    payout: 1200,
    deadline: '2026-04-29T18:00:00',
    postedAt: new Date(Date.now() - 60 * 60000).toISOString(),
    status: 'open',
    askerId: 'u4',
    askerName: 'Jordan Smith',
    askerAvatar: 'https://i.pravatar.cc/150?img=7',
    applicants: [],
    assignedDoerId: null,
    proof: null,
    requirements: ['Flyers will be provided', 'Take photos at each distribution point'],
    urgent: false,
  },
  {
    id: 't4',
    title: 'Fix Python Script Bug',
    category: 'Tech',
    description: 'My data analysis script is throwing a KeyError. Need someone with Python pandas knowledge to debug it.',
    location: 'Online / Remote',
    distance: 'Remote',
    payout: 600,
    deadline: '2026-04-28T20:00:00',
    postedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    status: 'open',
    askerId: 'u2',
    askerName: 'Alex Chen',
    askerAvatar: 'https://i.pravatar.cc/150?img=3',
    applicants: [],
    assignedDoerId: null,
    proof: null,
    requirements: ['Python + Pandas experience required', 'Script will be shared via GitHub'],
    urgent: false,
  },
  {
    id: 't5',
    title: 'Lab Record Submission',
    category: 'Errand',
    description: 'Submit my physics lab record to Prof. Kumar in Physics lab 3B. The record is at my hostel room, collect and submit.',
    location: 'Physics Lab 3B',
    distance: '0.8 km away',
    payout: 250,
    deadline: '2026-04-28T11:00:00',
    postedAt: new Date(Date.now() - 2 * 60000).toISOString(),
    status: 'assigned',
    askerId: 'u1',
    askerName: 'Arjun Mehra',
    askerAvatar: 'https://i.pravatar.cc/150?img=11',
    applicants: ['u2', 'u3', 'u4'],
    assignedDoerId: 'u5',
    proof: null,
    requirements: ['Collect from Room 204, Hostel C', 'Get acknowledgement slip from professor'],
    urgent: true,
  },
  {
    id: 't6',
    title: 'Library Book Delivery',
    category: 'Errand',
    description: 'Pick up 3 reserved books from the Main Library and deliver to North Hall lockers.',
    location: 'Main Library → North Hall',
    distance: '0.3 km away',
    payout: 450,
    deadline: '2026-04-28T16:00:00',
    postedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    status: 'pending_review',
    askerId: 'u1',
    askerName: 'Arjun Mehra',
    askerAvatar: 'https://i.pravatar.cc/150?img=11',
    applicants: ['u5'],
    assignedDoerId: 'u5',
    proof: {
      note: 'Delivered all 3 books to North Hall locker #42. Photo attached.',
      photos: [],
      submittedAt: new Date(Date.now() - 20 * 60000).toISOString(),
    },
    requirements: ['Books are reserved under Student ID 2024CS045', 'Take photo of delivery'],
    urgent: false,
  },
];

// Asker's active tasks (posted by current user)
export const MY_POSTED_TASKS = [
  {
    id: 'at1',
    title: 'Lab Report Formatting',
    category: 'Academic',
    payout: 800,
    status: 'open',
    applicantsCount: 3,
    postedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    deadline: '2026-04-28T17:00:00',
    location: 'Online',
    description: 'Format my physics lab report according to department guidelines. Template will be shared.',
  },
  {
    id: 'at2',
    title: 'Starbucks Delivery to Library',
    category: 'Errand',
    payout: 150,
    status: 'assigned',
    applicantsCount: 1,
    postedAt: new Date(Date.now() - 120 * 60000).toISOString(),
    deadline: '2026-04-27T19:00:00',
    location: 'Main Library, 2nd Floor',
    description: 'Get me a Venti Caramel Macchiato from Starbucks near Gate 2 and deliver to library.',
    assignedDoerName: 'James W.',
  },
];

// ─── MOCK EARNINGS ────────────────────────────────────────────────────────────
export const MOCK_EARNINGS = {
  total: 12450,
  pending: 1350,
  thisWeek: 2800,
  completedCount: 22,
  history: [
    { id: 'e1', title: 'Lab Report Formatting', date: '2026-04-26', amount: 800, status: 'settled', category: 'Academic', icon: 'description' },
    { id: 'e2', title: 'Spanish Essay Proofread', date: '2026-04-24', amount: 1200, status: 'settled', category: 'Academic', icon: 'translate' },
    { id: 'e3', title: 'Python Script Debug', date: '2026-04-22', amount: 600, status: 'settled', category: 'Tech', icon: 'code' },
    { id: 'e4', title: 'Hostel Room Moving', date: '2026-04-20', amount: 1500, status: 'settled', category: 'Labor', icon: 'inventory_2' },
    { id: 'e5', title: 'Lecture Notes Writing', date: '2026-04-18', amount: 500, status: 'pending', category: 'Academic', icon: 'history_edu' },
    { id: 'e6', title: 'Cafeteria Food Delivery', date: '2026-04-17', amount: 200, status: 'settled', category: 'Errand', icon: 'restaurant' },
    { id: 'e7', title: 'Assignment Submission', date: '2026-04-15', amount: 250, status: 'pending', category: 'Errand', icon: 'assignment_turned_in' },
  ],
  weeklyChart: [30, 45, 25, 85, 60, 50, 70], // percentage heights Mon-Sun
};

// ─── MOCK MESSAGES ────────────────────────────────────────────────────────────
export const MOCK_THREADS = [
  {
    id: 'thread1',
    participantId: 'u5',
    participantName: 'James W.',
    participantAvatar: 'https://i.pravatar.cc/150?img=8',
    taskTitle: 'Starbucks Delivery',
    lastMessage: "I'm at Starbucks now, order placed!",
    lastMessageTime: new Date(Date.now() - 5 * 60000).toISOString(),
    unread: 2,
    messages: [
      { id: 'm1', senderId: 'u1', text: 'Hi James, are you available to pick up my order?', time: new Date(Date.now() - 25 * 60000).toISOString() },
      { id: 'm2', senderId: 'u5', text: 'Yes! I\'m near Gate 2 already.', time: new Date(Date.now() - 22 * 60000).toISOString() },
      { id: 'm3', senderId: 'u1', text: 'Great, it\'s a Venti Caramel Macchiato. Extra shot please.', time: new Date(Date.now() - 18 * 60000).toISOString() },
      { id: 'm4', senderId: 'u5', text: "I'm at Starbucks now, order placed!", time: new Date(Date.now() - 5 * 60000).toISOString() },
    ],
  },
  {
    id: 'thread2',
    participantId: 'u2',
    participantName: 'Alex Chen',
    participantAvatar: 'https://i.pravatar.cc/150?img=3',
    taskTitle: 'Calculus Tutoring',
    lastMessage: 'Can we reschedule to 4 PM?',
    lastMessageTime: new Date(Date.now() - 2 * 3600000).toISOString(),
    unread: 0,
    messages: [
      { id: 'm5', senderId: 'u2', text: 'Hi! I applied for your tutoring task.', time: new Date(Date.now() - 4 * 3600000).toISOString() },
      { id: 'm6', senderId: 'u1', text: 'Great! Are you available at 3 PM?', time: new Date(Date.now() - 3.5 * 3600000).toISOString() },
      { id: 'm7', senderId: 'u2', text: 'Can we reschedule to 4 PM?', time: new Date(Date.now() - 2 * 3600000).toISOString() },
    ],
  },
];

// ─── MOCK DISPUTES ────────────────────────────────────────────────────────────
export const MOCK_DISPUTES = [
  {
    id: 'd1',
    taskId: 't6',
    taskTitle: 'Library Book Delivery',
    reason: 'incomplete',
    description: 'Only 2 of 3 books were delivered. The third book (Chemistry Vol 2) is missing.',
    status: 'under_review',
    raisedAt: new Date(Date.now() - 3600000).toISOString(),
    respondedAt: null,
    resolution: null,
  },
];

// ─── RECENT HISTORY (Asker view) ──────────────────────────────────────────────
export const ASKER_HISTORY = [
  { id: 'h1', title: 'Calculus Tutoring Session', date: '2026-04-20', paid: 1200, icon: 'menu_book', category: 'Academic' },
  { id: 'h2', title: 'Heavy Box Moving', date: '2026-04-18', paid: 2000, icon: 'inventory_2', category: 'Labor' },
  { id: 'h3', title: 'Hostel Grocery Run', date: '2026-04-15', paid: 400, icon: 'shopping_bag', category: 'Errand' },
];
